ninchatsdk/src/main/java/com/ninchat/sdk/NinchatSessionManager.java, ninchatsdk/src/main/java/com/ninchat/sdk/activities/NinchatActivity.java, ninchatsdk/src/main/java/com/ninchat/sdk/activities/NinchatChatActivity.java, ninchatsdk/src/main/java/com/ninchat/sdk/activities/NinchatQueueActivity.java, ninchatsdk/src/main/java/com/ninchat/sdk/managers/OrientationManager.java, ninchatsdk/src/main/java/com/ninchat/sdk/tasks/NinchatDeleteUserTask.java, ninchatsdk/src/main/java/com/ninchat/sdk/views/NinchatWebRTCView.java, ninchatsdk/src/main/res/layout/activity_ninchat_chat.xml, ninchatsdk/src/main/res/values-land/dimens.xml, ninchatsdk/src/main/res/values/dimens.xml
Fixes #85 
Fixes #59 
Fixes #61 
Fixes #82 
Fixes #84
=> Fix issues 85, 59, 61, 82 & 84

ninchatsdk/src/main/java/com/ninchat/sdk/NinchatSDKEventListener.java, ninchatsdk/src/main/java/com/ninchat/sdk/NinchatSession.java, ninchatsdk/src/main/java/com/ninchat/sdk/NinchatSessionManager.java, ninchatsdk/src/main/java/com/ninchat/sdk/activities/NinchatActivity.java, ninchatsdk/src/main/java/com/ninchat/sdk/activities/NinchatChatActivity.java, ninchatsdk/src/main/java/com/ninchat/sdk/activities/NinchatMediaActivity.java, ninchatsdk/src/main/java/com/ninchat/sdk/activities/NinchatQueueActivity.java, ninchatsdk/src/main/java/com/ninchat/sdk/adapters/NinchatMessageAdapter.java, ninchatsdk/src/main/java/com/ninchat/sdk/models/NinchatSessionCredentials.java, ninchatsdk/src/main/java/com/ninchat/sdk/tasks/NinchatOpenSessionTask.java, ninchatsdk/src/main/java/com/ninchat/sdk/views/NinchatWebRTCView.java, ninchatsdk/src/main/res/anim/slide_in_left.xml, ninchatsdk/src/main/res/anim/slide_out_right.xml, ninchatsdk/src/main/res/layout/activity_ninchat.xml
Add session persistence #94 
Add null handling for session manager, most likely fixing #74
Fix #93 
Fix #90 
Fix #80 
Fix #83
=> Merge develop to master

ninchatsdk/src/main/java/com/ninchat/sdk/NinchatSessionManager.java, ninchatsdk/src/main/java/com/ninchat/sdk/activities/NinchatActivity.java, ninchatsdk/src/main/java/com/ninchat/sdk/activities/NinchatChatActivity.java, ninchatsdk/src/main/java/com/ninchat/sdk/adapters/NinchatMessageAdapter.java, ninchatsdk/src/main/java/com/ninchat/sdk/adapters/NinchatQueueListAdapter.java, ninchatsdk/src/main/java/com/ninchat/sdk/models/NinchatFile.java, ninchatsdk/src/main/java/com/ninchat/sdk/models/NinchatMessage.java, ninchatsdk/src/main/res/values/dimens.xml
Fix various bugs
Following issues are fixed:
https://github.com/somia/mobile/issues/110
https://github.com/somia/mobile/issues/83
https://github.com/somia/mobile/issues/84
https://github.com/somia/mobile/issues/193
https://github.com/somia/mobile/issues/190
https://github.com/somia/mobile/issues/189
=> Various fixes

ninchatsdk/src/main/java/com/ninchat/sdk/NinchatConfiguration.java
More info
https://github.com/somia/mobile/issues/198
=> Consistent in builder patter.

ninchatsdk/src/main/res/layout/activity_ninchat_media.xml
Fixes https://github.com/somia/mobile/issues/195
=> Fix media title overflow

ninchatsdk/src/main/java/com/ninchat/sdk/activities/NinchatChatActivity.java, ninchatsdk/src/main/java/com/ninchat/sdk/adapters/NinchatMessageAdapter.java
More info
https://github.com/somia/mobile/issues/200
=> Opening softkeyboard hide message item

ninchatsdk/src/main/java/com/ninchat/sdk/NinchatSessionManager.java, ninchatsdk/src/main/java/com/ninchat/sdk/adapters/NinchatMessageAdapter.java
Add username/agentname overriding in chat
Fixes: https://github.com/somia/mobile/issues/89
=> Fix name override

build.gradle, ninchatsdk/build.gradle, ninchatsdk/src/test/java/com/ninchat/sdk/NinchatConfigurationTest.kt, ninchatsdk/src/test/java/com/ninchat/sdk/NinchatSessionManagerTest.kt, ninchatsdk/src/test/java/com/ninchat/sdk/NinchatSessionTest.kt, ninchatsdk/src/test/java/com/ninchat/sdk/models/NinchatFileTest.kt, ninchatsdk/src/test/java/com/ninchat/sdk/models/NinchatMessageTest.kt, ninchatsdk/src/test/java/com/ninchat/sdk/models/NinchatOptionTest.kt, ninchatsdk/src/test/java/com/ninchat/sdk/models/NinchatQueueTest.kt, ninchatsdk/src/test/java/com/ninchat/sdk/models/NinchatSessionCredentialsTest.kt, ninchatsdk/src/test/java/com/ninchat/sdk/models/NinchatUserTest.kt, ninchatsdk/src/test/java/com/ninchat/sdk/models/NinchatWebRTCServerInfoTest.kt, ninchatsdk/src/test/resources/mockito-extensions/org.mockito.plugins.MockMaker
Added initial unit tests
com.ninchat.sdk
```
class 16%
method 6%
line 5%
```
=> Added unit test for couple of classes

ninchatsdk/src/main/java/com/ninchat/sdk/NinchatSessionManager.java, ninchatsdk/src/main/java/com/ninchat/sdk/activities/NinchatQuestionnaireActivity.java, ninchatsdk/src/main/java/com/ninchat/sdk/activities/NinchatReviewActivity.java, ninchatsdk/src/main/java/com/ninchat/sdk/adapters/NinchatConversationQuestionnaireAdapter.java, ninchatsdk/src/main/java/com/ninchat/sdk/adapters/NinchatFormQuestionnaireAdapter.java, ninchatsdk/src/main/java/com/ninchat/sdk/adapters/NinchatQuestionnaireBaseAdapter.java, ninchatsdk/src/main/java/com/ninchat/sdk/adapters/holders/conversationview/NinchatConversationViewHolder.java, ninchatsdk/src/main/java/com/ninchat/sdk/adapters/holders/formview/NinchatButtonViewHolder.java, ninchatsdk/src/main/java/com/ninchat/sdk/adapters/holders/formview/NinchatInputFieldViewHolder.java, ninchatsdk/src/main/java/com/ninchat/sdk/events/OnAudienceRegistered.java, ninchatsdk/src/main/java/com/ninchat/sdk/events/OnNextQuestionnaire.java, ninchatsdk/src/main/java/com/ninchat/sdk/helper/questionnaire/NinchatQuestionnaireItemGetter.java, ninchatsdk/src/main/java/com/ninchat/sdk/helper/questionnaire/NinchatQuestionnaireMiscUtil.java, ninchatsdk/src/main/java/com/ninchat/sdk/helper/questionnaire/NinchatQuestionnaireSantizer.java, ninchatsdk/src/main/java/com/ninchat/sdk/models/questionnaire/NinchatQuestionnaire.java, ninchatsdk/src/main/java/com/ninchat/sdk/models/questionnaire/NinchatQuestionnaireBase.java, ninchatsdk/src/main/java/com/ninchat/sdk/models/questionnaire/NinchatQuestionnaireHolder.java, ninchatsdk/src/main/java/com/ninchat/sdk/models/questionnaire/conversation/NinchatConversationQuestionnaire.java, ninchatsdk/src/main/res/layout/bot_conversation_item.xml, ninchatsdk/src/main/res/layout/review_rating_bot_view.xml
More details regarding fix list 
https://github.com/somia/mobile/issues/252
=> Bugfixes and improvements based on first phase of testing.

ninchatsdk/src/main/java/com/ninchat/sdk/adapters/holders/conversationview/NinchatConversationViewHolder.java, ninchatsdk/src/main/java/com/ninchat/sdk/adapters/holders/formview/NinchatButtonViewHolder.java, ninchatsdk/src/main/java/com/ninchat/sdk/helper/questionnaire/NinchatQuestionnaireItemGetter.java, ninchatsdk/src/main/java/com/ninchat/sdk/helper/questionnaire/NinchatQuestionnaireItemSetter.java, ninchatsdk/src/main/java/com/ninchat/sdk/models/questionnaire/NinchatQuestionnaireBase.java, ninchatsdk/src/main/java/com/ninchat/sdk/models/questionnaire/conversation/NinchatConversationQuestionnaire.java, ninchatsdk/src/main/java/com/ninchat/sdk/models/questionnaire/form/NinchatFormQuestionnaire.java, ninchatsdk/src/main/res/drawable/ninchat_border_with_error.xml, ninchatsdk/src/main/res/drawable/ninchat_border_with_focus.xml, ninchatsdk/src/main/res/drawable/ninchat_border_with_ok.xml, ninchatsdk/src/main/res/drawable/ninchat_border_with_unfocus.xml, ninchatsdk/src/main/res/drawable/ninchat_ui_compose_select_button.xml, ninchatsdk/src/main/res/layout/control_buttons.xml, ninchatsdk/src/main/res/values/questionnaire_styles.xml
Review feedback and improvements
More details
https://github.com/somia/mobile/issues/252
=> Navigation improvements

ninchatsdk/src/main/java/com/ninchat/sdk/NinchatSessionManager.java, ninchatsdk/src/main/java/com/ninchat/sdk/activities/NinchatActivity.java, ninchatsdk/src/main/java/com/ninchat/sdk/adapters/NinchatQueueListAdapter.java, ninchatsdk/src/main/java/com/ninchat/sdk/helper/questionnaire/NinchatQuestionnaireItemGetter.java, ninchatsdk/src/main/java/com/ninchat/sdk/models/questionnaire/conversation/NinchatConversationQuestionnaire.java, ninchatsdk/src/main/res/layout/activity_ninchat_chat.xml, ninchatsdk/src/main/res/layout/text_area.xml, ninchatsdk/src/main/res/layout/text_field.xml
More details
https://github.com/somia/mobile/issues/260
=> SDK bugfixes

ninchatsdk/src/main/res/drawable/ninchat_radio_select_button.xml, ninchatsdk/src/main/res/values/questionnaire_styles.xml
Added styling feedback 
- Increase padding for selected options item
- Increase padding for the questionnaire input field
=> Add missing styling from feedback

ninchatsdk/src/main/java/com/ninchat/sdk/NinchatSessionManager.java, ninchatsdk/src/main/java/com/ninchat/sdk/activities/NinchatChatActivity.java, ninchatsdk/src/main/java/com/ninchat/sdk/activities/NinchatQueueActivity.java, ninchatsdk/src/main/java/com/ninchat/sdk/helper/questionnaire/NinchatQuestionnaireTypeUtil.java, ninchatsdk/src/main/java/com/ninchat/sdk/models/questionnaire/NinchatQuestionnaireBase.java, ninchatsdk/src/main/java/com/ninchat/sdk/tasks/NinchatDescribeChannelTask.java
More detials
https://github.com/somia/mobile/issues/264
=> Session Resuming Logic Improvements

.idea/modules.xml, ninchatsdk/src/main/java/com/ninchat/sdk/NinchatSessionManager.java, ninchatsdk/src/main/java/com/ninchat/sdk/helper/session/NinchatSessionManagerHelper.kt
Issue: Chat close view was showing after a transfer happens due to a cached chat adapter.
Affected version v0.8.0 ( pre-release )
=> Fix close chat when transfer

ninchatsdk/src/main/res/values/styles.xml
More details 
https://github.com/somia/mobile/issues/316
=> Fix - use spec specific color asset attribute for submit button.

README.md, ninchatsdk/src/main/res/layout/activity_ninchat_chat.xml, ninchatsdk/src/main/res/values/colors.xml
Add missing ninchat_color_textarea_text
- which should change the chat input field text color
Also introduced ninchat_color_textarea_text_hint
- So, user can override the hints as well
=> Add missing ninchat_color_textarea_text

ninchatsdk/src/main/java/com/ninchat/sdk/ninchatquestionnaire/helper/NinchatQuestionnaireJsonUtil.kt, ninchatsdk/src/main/java/com/ninchat/sdk/ninchatquestionnaire/ninchatquestionnairelist/model/NinchatQuestionnaireListModel.kt
More details
- https://github.com/somia/mobile/issues/323
=> Fix questionnaire traversal logic

README.md, ninchatsdk/src/main/java/com/ninchat/sdk/NinchatSessionManager.java, ninchatsdk/src/main/java/com/ninchat/sdk/activities/NinchatChatActivity.java, ninchatsdk/src/main/java/com/ninchat/sdk/adapters/NinchatMessageAdapter.java, ninchatsdk/src/main/java/com/ninchat/sdk/utils/misc/Misc.kt, ninchatsdk/src/main/res/layout/activity_ninchat_chat.xml, ninchatsdk/src/main/res/values/colors.xml
Add view recycler inconsistency fix
- By increasing view offset padding
- https://github.com/somia/mobile/issues/320
=> Add view recycler inconsistency fix

ninchatsdk/src/main/java/com/ninchat/sdk/ninchatquestionnaire/helper/NinchatQuestionnaireNormalizer.kt, ninchatsdk/src/main/java/com/ninchat/sdk/utils/threadutils/NinchatScopeHandler.kt
Questionnaire showing redundant button element even though site config explicitly put it false
=> Redundant navigation button element

ninchatsdk/src/main/java/com/ninchat/sdk/ninchatquestionnaire/ninchatdropdownselect/view/NinchatDropDownSelectViewHolder.kt, ninchatsdk/src/main/res/layout/dropdown_list.xml
Make caret icon clickable too
- Does not fully comply with given UI but still better than not being able to click the caret. 
- Will work more improvement later
=> Dropdown menu - Make caret clickable

ninchatsdk/src/main/java/com/ninchat/sdk/ninchatquestionnaire/ninchatradiobutton/view/NinchatRadioButtonView.kt, ninchatsdk/src/main/java/com/ninchat/sdk/ninchatquestionnaire/ninchatradiobuttonlist/view/NinchatRadioButtonListView.kt
- Multiple radio button element can sometimes be marked as selected
=> Bugfix Radio button UI element

ninchatsdk/src/main/java/com/ninchat/sdk/adapters/NinchatMultiChoiceAdapter.java
More details:
https://github.com/somia/mobile/issues/329
=> UI Actions

ninchatsdk/src/main/java/com/ninchat/sdk/helper/session/NinchatSessionManagerHelper.kt, ninchatsdk/src/main/java/com/ninchat/sdk/ninchatqueue/model/NinchatQueueModel.kt, ninchatsdk/src/main/java/com/ninchat/sdk/ninchatqueue/presenter/NinchatQueuePresenter.kt
More details
- https://github.com/somia/mobile/issues/328
=> Show queue close message when a queue is closed.

ninchatsdk/build.gradle, ninchatsdk/src/main/java/com/ninchat/sdk/adapters/NinchatMessageAdapter.java, ninchatsdk/src/main/java/com/ninchat/sdk/models/NinchatMessage.java, ninchatsdk/src/main/java/com/ninchat/sdk/ninchatchatmessage/NinchatMessageList.kt, ninchatsdk/src/main/java/com/ninchat/sdk/utils/misc/Misc.kt
This is just a PoC where I am and will trying to find a way to resolve
- RV can handle frequent recycler view update ( add/delete/update messages in millisecond interval )
- Backpressure based incoming message handling
- A more crash-free view adapter
**_It is probably not going to merge in `develop` anytime soon unless I am confident that the given solution is better than the existing solution and giving us a significant edge._**
=> Improved chat RH view adapter 

ninchatsdk/src/main/java/com/ninchat/sdk/ninchatquestionnaire/helper/NinchatQuestionnaireNormalizer.kt
More details
- https://github.com/somia/mobile/issues/334
=> Update logic on when to apply navigation

ninchatsdk/src/main/java/com/ninchat/sdk/ninchatquestionnaire/helper/NinchatQuestionnaireJsonUtil.kt, ninchatsdk/src/main/java/com/ninchat/sdk/ninchatquestionnaire/helper/NinchatQuestionnaireNormalizer.kt, ninchatsdk/src/main/java/com/ninchat/sdk/ninchatquestionnaire/helper/NinchatQuestionnaireType.kt
More details
https://github.com/somia/mobile/issues/333
=> Show button logic fix

ninchatsdk/src/main/java/com/ninchat/sdk/NinchatConfiguration.kt, ninchatsdk/src/main/java/com/ninchat/sdk/NinchatSessionManager.java, ninchatsdk/src/main/java/com/ninchat/sdk/activities/NinchatChatActivity.java, ninchatsdk/src/main/java/com/ninchat/sdk/ninchatquestionnaire/ninchatquestionnaireactivity/view/NinchatQuestionnaireActivity.kt, ninchatsdk/src/main/java/com/ninchat/sdk/ninchatreview/presenter/NinchatReviewPresenter.kt, ninchatsdk/src/main/java/com/ninchat/sdk/utils/misc/Misc.kt
More details
https://github.com/somia/mobile/issues/336
=> Support setting one time chat background

ninchatsdk/src/main/java/com/ninchat/sdk/activities/NinchatChatActivity.java, ninchatsdk/src/main/java/com/ninchat/sdk/states/NinchatState.kt, ninchatsdk/src/main/java/com/ninchat/sdk/utils/writingindicator/WritingIndicator.kt
More details
- https://github.com/somia/mobile/issues/338
=> Crashlytics bug fixes from recent release

ninchatsdk/src/main/java/com/ninchat/sdk/NinchatSessionManager.java, ninchatsdk/src/main/java/com/ninchat/sdk/activities/NinchatChatActivity.java, ninchatsdk/src/main/java/com/ninchat/sdk/helper/session/NinchatSessionManagerHelper.kt, ninchatsdk/src/main/java/com/ninchat/sdk/ninchatactivity/presenter/NinchatActivityPresenter.kt, ninchatsdk/src/main/java/com/ninchat/sdk/ninchatactivity/view/NinchatActivity.kt, ninchatsdk/src/main/java/com/ninchat/sdk/ninchatquestionnaire/ninchatquestionnaireactivity/model/NinchatQuestionnaireModel.kt, ninchatsdk/src/main/java/com/ninchat/sdk/ninchatqueue/model/NinchatQueueModel.kt, ninchatsdk/src/main/java/com/ninchat/sdk/ninchatreview/presenter/NinchatReviewPresenter.kt, ninchatsdk/src/main/java/com/ninchat/sdk/states/NinchatState.kt
Now, if a user clicks skip in the rating view, post audience questionnaire ( if there is any ) should not be shown
More details
https://github.com/somia/mobile/issues/342
=> Use case improvement: Skip in rating view

ninchatsdk/src/main/java/com/ninchat/sdk/helper/session/NinchatSessionHolder.kt
Multiple SDK client session issue
https://github.com/somia/mobile/issues/348
=> bugfix: close session when SDK dispose is called.

ninchatsdk/src/main/java/com/ninchat/sdk/helper/siteconfigparser/NinchatSiteConfig.kt, ninchatsdk/src/main/java/com/ninchat/sdk/models/NinchatTitlebarInfo.kt, ninchatsdk/src/main/java/com/ninchat/sdk/ninchatactivity/view/NinchatActivity.kt, ninchatsdk/src/main/java/com/ninchat/sdk/ninchatquestionnaire/ninchatbotwriting/view/NinchatBotWriting.kt, ninchatsdk/src/main/java/com/ninchat/sdk/ninchatquestionnaire/ninchatquestionnaireactivity/presenter/NinchatQuestionnairePresenter.kt, ninchatsdk/src/main/java/com/ninchat/sdk/ninchatquestionnaire/ninchatquestionnaireactivity/view/NinchatQuestionnaireActivity.kt, ninchatsdk/src/main/java/com/ninchat/sdk/ninchatqueue/presenter/NinchatQueuePresenter.kt, ninchatsdk/src/main/res/layout/activity_ninchat_questionnaire.xml, ninchatsdk/src/main/res/layout/bot_item_conversation_view.xml, ninchatsdk/src/main/res/layout/ninchat_titlebar.xml
Support titlebar in pre audience questionnaire
- No questionnaire avatar or questionnaire name
- Show placeholder
- Has questionnaire avatar and questionnaire name
- Show questionnare avatar and questionnair name
- No questionnaire avatar and has questionnaire name
- Only show questionnaire name
=> titlebar: pre audience questionnaire

ninchatsdk/src/main/res/layout/review_rating_icon_items.xml
Rating view order change to
`Poor - Ok - Good`
More details:
https://github.com/somia/mobile/issues/353
=> rating view: reverse the order in rating view

ninchatsdk/src/main/java/com/ninchat/sdk/activities/NinchatChatActivity.java
More details
- https://github.com/somia/mobile/issues/355
=> rotation - backlog view should respect system rotation preference

ninchatsdk/src/main/java/com/ninchat/sdk/helper/siteconfigparser/NinchatSiteConfig.kt, ninchatsdk/src/main/java/com/ninchat/sdk/ninchatreview/model/NinchatReviewModel.kt, ninchatsdk/src/main/java/com/ninchat/sdk/ninchatreview/presenter/NinchatReviewPresenter.kt, ninchatsdk/src/main/res/layout/activity_ninchat_review.xml, ninchatsdk/src/main/res/layout/review_rating_bot_view.xml
More details
- https://github.com/somia/mobile/issues/346
=> Add support for rating info text

ninchatsdk/src/main/res/values/styles.xml
More details 
https://github.com/somia/mobile/issues/354
=> closebutton: sync close button styling resources

ninchatsdk/src/main/java/com/ninchat/sdk/activities/NinchatChatActivity.java, ninchatsdk/src/main/java/com/ninchat/sdk/views/NinchatWebRTCView.java
Titlebar should not be shown
- When in landscape view and there is an ongoing video call
=> titlebar: don't show in full screen video view

ninchatsdk/src/main/java/com/ninchat/sdk/NinchatSessionManager.java, ninchatsdk/src/main/java/com/ninchat/sdk/activities/NinchatChatActivity.java, ninchatsdk/src/main/java/com/ninchat/sdk/adapters/NinchatMessageAdapter.java, ninchatsdk/src/main/java/com/ninchat/sdk/helper/session/NinchatSessionManagerHelper.kt, ninchatsdk/src/main/java/com/ninchat/sdk/models/NinchatMessage.java, ninchatsdk/src/main/java/com/ninchat/sdk/ninchatchatmessage/NinchatMessageList.kt, ninchatsdk/src/main/java/com/ninchat/sdk/ninchatquestionnaire/ninchatbotwriting/view/NinchatBotWriting.kt, ninchatsdk/src/main/java/com/ninchat/sdk/ninchatquestionnaire/ninchatradiobutton/view/NinchatRadioButtonView.kt, ninchatsdk/src/main/java/com/ninchat/sdk/ninchatquestionnaire/ninchatradiobuttonlist/view/NinchatRadioButtonListView.kt, ninchatsdk/src/main/java/com/ninchat/sdk/utils/misc/Misc.kt, ninchatsdk/src/main/res/drawable/ninchat_chat_command_input_text.xml, ninchatsdk/src/main/res/drawable/ninchat_chat_info.xml, ninchatsdk/src/main/res/drawable/ninchat_icon_chat_info_icon.xml, ninchatsdk/src/main/res/drawable/ninchat_questionnaire_bot_view.xml, ninchatsdk/src/main/res/drawable/ninchat_ui_compose_select_button.xml, ninchatsdk/src/main/res/drawable/ninchat_ui_compose_select_button_selected.xml, ninchatsdk/src/main/res/layout/activity_ninchat_chat.xml, ninchatsdk/src/main/res/layout/bot_item_conversation_view.xml, ninchatsdk/src/main/res/layout/bot_writing_indicator.xml, ninchatsdk/src/main/res/layout/checkbox_compound.xml, ninchatsdk/src/main/res/layout/item_chat_message.xml, ninchatsdk/src/main/res/layout/multichoice_with_label.xml, ninchatsdk/src/main/res/layout/radio_item.xml, ninchatsdk/src/main/res/values/colors.xml, ninchatsdk/src/main/res/values/config.xml, ninchatsdk/src/main/res/values/dimens.xml, ninchatsdk/src/main/res/values/strings.xml, ninchatsdk/src/main/res/values/styles.xml
- ##### `Style/Theme component`
- ##### `Resource`
- ##### `Icon`
- ##### `Dimen`
- ##### `Background`
- ##### `Color`
`*Bot writing indicator ( bubble )*`
- `Same as writing indicator in backlog / chat view`
- `Speech bubble - ( Enforcing from ninchat. )`
=> botview: bot view syling

ninchatsdk/src/main/java/com/ninchat/sdk/ninchatquestionnaire/ninchatbotwriting/presenter/NinchatBotWritingViewPresenter.kt, ninchatsdk/src/main/java/com/ninchat/sdk/ninchatquestionnaire/ninchatbotwriting/view/NinchatBotWriting.kt
More details
https://github.com/somia/mobile/issues/366
=> Questionnaire avatar visibility

ninchatsdk/src/main/java/com/ninchat/sdk/helper/session/NinchatSessionHolder.kt
A workaround for handling guest user deletion when connection is inactive for long time
More details about the issue
- https://github.com/somia/mobile/issues/368#issuecomment-966285888
=> user_not_found event handling

ninchatsdk/src/main/java/com/ninchat/sdk/helper/session/NinchatSessionManagerHelper.kt, ninchatsdk/src/main/java/com/ninchat/sdk/ninchatquestionnaire/ninchatquestionnaireactivity/presenter/NinchatQuestionnairePresenter.kt, ninchatsdk/src/main/java/com/ninchat/sdk/ninchatquestionnaire/ninchatquestionnaireactivity/view/NinchatQuestionnaireActivity.kt, ninchatsdk/src/main/java/com/ninchat/sdk/states/NinchatState.kt
More details
https://github.com/somia/mobile/issues/371
=> Show pre-answer in backlog

ninchatsdk/src/main/java/com/ninchat/sdk/activities/NinchatChatActivity.java
Bugfix in titlebar visibility. More details
https://github.com/somia/mobile/issues/372
=> Handle titlebar visibility in different orientation

ninchatsdk/src/main/java/com/ninchat/sdk/ninchatquestionnaire/ninchatquestionnairelist/presenter/NinchatConversationListPresenter.kt, ninchatsdk/src/main/java/com/ninchat/sdk/ninchatquestionnaire/ninchatquestionnairelist/presenter/NinchatFormListPresenter.kt, ninchatsdk/src/main/java/com/ninchat/sdk/ninchatquestionnaire/ninchatquestionnairelist/presenter/NinchatQuestionnaireListPresenter.kt
More details ( part 2 )
https://github.com/somia/mobile/issues/385
=> support target: "_close"

ninchatsdk/src/main/java/com/ninchat/sdk/helper/glidewrapper/GlideWrapper.java, ninchatsdk/src/main/java/com/ninchat/sdk/ninchatmedia/model/NinchatMediaModel.kt, ninchatsdk/src/main/java/com/ninchat/sdk/ninchatmedia/presenter/NinchatMediaPresenter.kt, ninchatsdk/src/main/java/com/ninchat/sdk/ninchatmedia/view/NinchatMediaActivity.kt, ninchatsdk/src/main/res/drawable/ninchat_file_preview_loader.xml, ninchatsdk/src/main/res/layout/activity_ninchat_media.xml, ninchatsdk/src/main/res/values/strings.xml
Loader animation while image is being previewed for download.
More details : 
https://github.com/somia/mobile/issues/383
=> feature: loader animation

ninchatsdk/src/main/AndroidManifest.xml
More details:
https://github.com/somia/mobile/issues/393
=> Orientation change change display text

ninchatsdk/src/main/java/com/ninchat/sdk/ninchatquestionnaire/ninchathyperlink/presenter/OnClickListener.kt, ninchatsdk/src/main/java/com/ninchat/sdk/ninchatquestionnaire/ninchathyperlink/view/NinchatHyperLinkViewHolder.kt
More details:
https://github.com/somia/mobile/issues/402
=> HyperlinkElement: Add throttling to button click event

ninchatsdk/src/main/java/com/ninchat/sdk/ninchatquestionnaire/helper/NinchatQuestionnaireJsonUtil.kt
More details:
https://github.com/somia/mobile/issues/403
=> HyperlinkElement: don't send selected hyperlink element value

ninchatsdk/src/main/java/com/ninchat/sdk/NinchatSessionManager.java, ninchatsdk/src/main/java/com/ninchat/sdk/activities/NinchatChatActivity.java, ninchatsdk/src/main/java/com/ninchat/sdk/adapters/NinchatMessageAdapter.java, ninchatsdk/src/main/java/com/ninchat/sdk/helper/message/NinchatMessageService.kt, ninchatsdk/src/main/java/com/ninchat/sdk/helper/propsparser/NinchatPropsParser.kt, ninchatsdk/src/main/java/com/ninchat/sdk/helper/session/NinchatSessionManagerHelper.kt, ninchatsdk/src/main/java/com/ninchat/sdk/models/NinchatMessage.java, ninchatsdk/src/main/java/com/ninchat/sdk/models/NinchatUser.java, ninchatsdk/src/main/java/com/ninchat/sdk/ninchatmedia/model/NinchatFile.kt, ninchatsdk/src/main/java/com/ninchat/sdk/ninchattitlebar/model/NinchatTitlebar.kt, ninchatsdk/src/test/java/com/ninchat/sdk/models/NinchatUserTest.kt
More details:
https://github.com/somia/mobile/issues/405
=> Overlapping channel message problem

build.gradle, ninchatsdk/build.gradle, ninchatsdk/src/main/java/com/ninchat/sdk/views/NinchatWebRTCView.java
Update WebRTC library to ~M104
=> update webRTC library

build.gradle, gradle/wrapper/gradle-wrapper.properties, ninchatsdk/build.gradle, ninchatsdk/src/main/java/com/ninchat/sdk/NinchatSessionManager.java, ninchatsdk/src/main/java/com/ninchat/sdk/helper/propsparser/NinchatPropsParser.kt, ninchatsdk/src/main/java/com/ninchat/sdk/helper/session/NinchatSessionHolder.kt, ninchatsdk/src/main/java/com/ninchat/sdk/helper/session/NinchatSessionManagerHelper.kt, ninchatsdk/src/main/java/com/ninchat/sdk/networkdispatchers/NinchatDiscoverJitsi.kt, ninchatsdk/src/main/java/com/ninchat/sdk/ninchatchatactivity/NinchatChatPresenter.kt, ninchatsdk/src/main/java/com/ninchat/sdk/ninchatqueuelist/model/NinchatQueue.kt, ninchatsdk/src/main/java/com/ninchat/sdk/utils/messagetype/NinchatMessageTypes.kt, ninchatsdk/src/main/java/com/ninchat/sdk/utils/misc/Misc.kt
More details in following comments
=> group video integration: Jitsi library

ninchatsdk/src/main/java/com/ninchat/sdk/helper/propsparser/NinchatPropsParser.kt, ninchatsdk/src/main/java/com/ninchat/sdk/helper/session/NinchatSessionHolder.kt, ninchatsdk/src/main/java/com/ninchat/sdk/helper/session/NinchatSessionManagerHelper.kt, ninchatsdk/src/main/java/com/ninchat/sdk/ninchatchatactivity/view/NinchatChatActivity.kt, ninchatsdk/src/main/java/com/ninchat/sdk/ninchatqueuelist/model/NinchatQueue.kt, ninchatsdk/src/main/java/com/ninchat/sdk/states/NinchatState.kt
Determine group/conference call based on channel attributes
=> Fix group call type detection

ninchatsdk/src/main/java/com/ninchat/sdk/helper/siteconfigparser/NinchatSiteConfig.kt, ninchatsdk/src/main/java/com/ninchat/sdk/ninchatchatactivity/model/NinchatChatModel.kt, ninchatsdk/src/main/java/com/ninchat/sdk/ninchatchatactivity/view/NinchatChatActivity.kt, ninchatsdk/src/main/java/com/ninchat/sdk/ninchatvideointegrations/jitsi/NinchatGroupCallIntegration.kt, ninchatsdk/src/main/java/com/ninchat/sdk/ninchatvideointegrations/jitsi/model/NinchatGroupCallModel.kt, ninchatsdk/src/main/java/com/ninchat/sdk/ninchatvideointegrations/jitsi/presenter/NinchatGroupCallPresenter.kt, ninchatsdk/src/main/java/com/ninchat/sdk/ninchatvideointegrations/jitsi/presenter/OnClickListener.kt, ninchatsdk/src/main/java/com/ninchat/sdk/ninchatvideointegrations/p2p/NinchatP2PIntegration.kt, ninchatsdk/src/main/res/drawable/ninchat_icon_video_conference.xml, ninchatsdk/src/main/res/layout/activity_ninchat_chat.xml, ninchatsdk/src/main/res/layout/ninchat_join_end_conference.xml, ninchatsdk/src/main/res/layout/ninchat_p2p_video_container.xml, ninchatsdk/src/main/res/values/dimens.xml, ninchatsdk/src/main/res/values/styles.xml
More details
https://github.com/somia/mobile/issues/426
=> Join and leave a group video meeting page

ninchatsdk/proguard-rules.pro, ninchatsdk/src/main/AndroidManifest.xml, ninchatsdk/src/main/java/com/ninchat/sdk/activities/NinchatBaseActivity.kt, ninchatsdk/src/main/java/com/ninchat/sdk/events/OnNewMessage.java, ninchatsdk/src/main/java/com/ninchat/sdk/helper/message/NinchatMessageService.kt, ninchatsdk/src/main/java/com/ninchat/sdk/helper/session/NinchatSessionManagerHelper.kt, ninchatsdk/src/main/java/com/ninchat/sdk/ninchatchatactivity/model/NinchatChatModel.kt, ninchatsdk/src/main/java/com/ninchat/sdk/ninchatchatactivity/presenter/NinchatChatPresenter.kt, ninchatsdk/src/main/java/com/ninchat/sdk/ninchatchatactivity/view/NinchatChatActivity.kt, ninchatsdk/src/main/java/com/ninchat/sdk/ninchatchatactivity/view/NinchatChatBroadcastManager.kt, ninchatsdk/src/main/java/com/ninchat/sdk/ninchatchatactivity/view/SoftKeyboardViewHandler.kt, ninchatsdk/src/main/java/com/ninchat/sdk/ninchattitlebar/model/NinchatTitlebar.kt, ninchatsdk/src/main/java/com/ninchat/sdk/ninchattitlebar/view/NinchatTitlebarView.kt, ninchatsdk/src/main/java/com/ninchat/sdk/ninchatvideointegrations/jitsi/NinchatGroupCallIntegration.kt, ninchatsdk/src/main/java/com/ninchat/sdk/ninchatvideointegrations/jitsi/model/NinchatGroupCallModel.kt, ninchatsdk/src/main/java/com/ninchat/sdk/ninchatvideointegrations/jitsi/presenter/NinchatGroupCallPresenter.kt, ninchatsdk/src/main/java/com/ninchat/sdk/ninchatvideointegrations/p2p/NinchatP2PIntegration.kt, ninchatsdk/src/main/java/com/ninchat/sdk/utils/messagetype/NinchatMessageTypes.kt, ninchatsdk/src/main/java/com/ninchat/sdk/utils/misc/Misc.kt, ninchatsdk/src/main/res/drawable/ninchat_icon_toggle_chat_bubble.xml, ninchatsdk/src/main/res/drawable/ninchat_icon_toggle_chat_bubble_new_message.xml, ninchatsdk/src/main/res/drawable/ninchat_titlebar_toggle_chat_button.xml, ninchatsdk/src/main/res/layout/activity_ninchat_chat.xml, ninchatsdk/src/main/res/layout/ninchat_titlebar.xml, ninchatsdk/src/main/res/values/dimens.xml, ninchatsdk/src/main/res/values/styles.xml
Known issue:
- video flickering on pixel 3a XL
=> Jitsi view implementation refactoring

ninchatsdk/src/main/java/com/ninchat/sdk/activities/NinchatBaseActivity.kt, ninchatsdk/src/main/java/com/ninchat/sdk/ninchatchatactivity/view/NinchatChatActivity.kt, ninchatsdk/src/main/java/com/ninchat/sdk/ninchatchatactivity/view/NinchatChatBroadcastManager.kt, ninchatsdk/src/main/java/com/ninchat/sdk/ninchatvideointegrations/jitsi/NinchatGroupCallIntegration.kt, ninchatsdk/src/main/java/com/ninchat/sdk/ninchatvideointegrations/jitsi/presenter/NinchatGroupCallPresenter.kt, ninchatsdk/src/main/res/drawable/ninchat_translucent_background.xml, ninchatsdk/src/main/res/layout/activity_ninchat_chat.xml, ninchatsdk/src/main/res/values/styles.xml
Ability to toggle/close chat by clicking jitsi video view
=> Toggle/close chat with from Jitsi view view

ninchatsdk/src/main/java/com/ninchat/sdk/ninchatvideointegrations/jitsi/NinchatGroupCallIntegration.kt, ninchatsdk/src/main/res/drawable/ninchat_translucent_background.xml
- Participants in jitsi meeting view should be disabled
- Set background opacity in on going view video based on review feedback
=> Review feedback

ninchatsdk/src/main/java/com/ninchat/sdk/helper/siteconfigparser/NinchatSiteConfig.kt, ninchatsdk/src/main/java/com/ninchat/sdk/ninchatvideointegrations/jitsi/NinchatGroupCallIntegration.kt
Use https://ninchat.com/new/jitsi-meet.html to load jitsi embed page just like iOS
=> embed: use external url

ninchatsdk/src/main/java/com/ninchat/sdk/ninchatchatactivity/view/NinchatVideoChatConsentDialogue.kt, ninchatsdk/src/main/java/com/ninchat/sdk/ninchatvideointegrations/p2p/NinchatP2PIntegration.kt
Fix wrong key was was used for modal consent description and modal accept button text
=> bugfix: wrong description and button text

ninchatsdk/src/main/AndroidManifest.xml, ninchatsdk/src/main/java/com/ninchat/sdk/activities/NinchatBaseActivity.kt, ninchatsdk/src/main/java/com/ninchat/sdk/ninchatchatactivity/view/NinchatChatActivity.kt, ninchatsdk/src/main/java/com/ninchat/sdk/ninchatmedia/view/NinchatMediaActivity.kt, ninchatsdk/src/main/java/com/ninchat/sdk/ninchatvideointegrations/jitsi/NinchatGroupCallIntegration.kt, ninchatsdk/src/main/java/com/ninchat/sdk/ninchatvideointegrations/p2p/NinchatP2PIntegration.kt, ninchatsdk/src/main/java/com/ninchat/sdk/utils/permission/NinchatPermission.kt
More details
- https://github.com/somia/mobile/issues/449
=> permission: file permission change

ninchatsdk/src/main/java/com/ninchat/sdk/managers/webrtc/VolumeController.kt, ninchatsdk/src/main/java/com/ninchat/sdk/ninchatvideointegrations/jitsi/NinchatGroupCallIntegration.kt
=> Custom volume control 
